### ISSUE TITLE
: avant un émoji perturbe le bot

### ISSUE THREAD

**Issue by awing-ding** [max-208/AlterBot#8]
Pour la fonctionnalité sondage, ajouter un : avant un émoji de serveur fait planter le bot. Nécessite plus d'investigations.

**Comment by max-208** [comment]
J'ai regardé, c'est l'emoji âne, il fait partie de nouveaux emojis il faudra probablement mettre a jour la regex pour inclure les nouveaux emojis

**Comment by awing-ding** [comment]
> J'ai regardé, c'est l'emoji âne, il fait partie de nouveaux emojis il faudra probablement mettre a jour la regex pour inclure les nouveaux emojis

Les nouveaux emojis sont normalement ajouté par la pr #7 mais ce bug est différent, il survient quand le : est avant des emojis de serveur. Le fix est probablement aussi dans la regex tho. ![exemple du problème](https://github.com/user-attachments/assets/726f579b-795f-4524-952a-c34a4cb32815)
